'use client'

import { use, useEffect, useMemo, useState } from 'react'
import { getRepo } from '@/lib/repo'
import { buildKitchenSheet, DIETARY_CATEGORIES } from '@/lib/kitchen'
import type { Guest, VenueTable, WeddingEvent } from '@/lib/types'

/**
 * The caterer's view: per-table plate counts + allergy notes, printed via
 * the browser (window.print) so CJK guest names render correctly.
 */
export default function KitchenPage({
  params,
}: {
  params: Promise<{ eventId: string }>
}) {
  const { eventId } = use(params)
  const [event, setEvent] = useState<WeddingEvent | null>(null)
  const [tables, setTables] = useState<VenueTable[]>([])
  const [guests, setGuests] = useState<Guest[]>([])

  useEffect(() => {
    ;(async () => {
      const repo = getRepo()
      const e = await repo.getEvent(eventId)
      if (!e) return
      const [l, gs] = await Promise.all([repo.getLayout(e.layout_id), repo.listGuests(eventId)])
      setEvent(e)
      setTables(l?.tables ?? [])
      setGuests(gs)
    })()
  }, [eventId])

  const sheet = useMemo(() => buildKitchenSheet(tables, guests), [tables, guests])
  if (!event) return <p className="p-8 text-sm text-slate-400">Loading…</p>

  const showUnassigned = sheet.unassigned.pax > 0

  return (
    <div className="mx-auto max-w-4xl px-6 py-8">
      {/* everything outside .print-area is hidden when printing */}
      <style>{`
        @media print {
          body * { visibility: hidden; }
          .print-area, .print-area * { visibility: visible; }
          .print-area { position: absolute; inset: 0; width: 100%; }
          @page { margin: 12mm; }
        }
      `}</style>

      <div className="no-print mb-6 flex items-center justify-between">
        <h1 className="text-xl font-bold text-slate-900">Kitchen sheet</h1>
        <button
          onClick={() => window.print()}
          className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-700"
        >
          Print / save as PDF
        </button>
      </div>

      <div className="print-area">
        <div className="mb-1 text-lg font-bold text-slate-900">
          {event.couple_names} — {event.event_date}
        </div>
        <p className="mb-4 text-sm text-slate-500">
          {sheet.totals.pax} pax ·{' '}
          {DIETARY_CATEGORIES.map((c) => `${sheet.totals.counts[c.key]} ${c.label.toLowerCase()}`).join(' · ')}
          {sheet.totals.allergies > 0 && ` · ${sheet.totals.allergies} allergy ${sheet.totals.allergies === 1 ? 'note' : 'notes'}`}
        </p>

        {sheet.clampedGuests.length > 0 && (
          <p className="mb-4 rounded-md border border-amber-300 bg-amber-50 px-3 py-2 text-xs text-amber-800">
            Counts capped at party size for: {sheet.clampedGuests.join(', ')} — their party shrank
            after dietary needs were recorded. Please confirm with them.
          </p>
        )}

        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="border-b-2 border-slate-300 text-left text-xs uppercase tracking-wide text-slate-500">
              <th className="py-2 pr-3">Table</th>
              <th className="py-2 pr-3">Pax</th>
              {DIETARY_CATEGORIES.map((c) => (
                <th key={c.key} className="py-2 pr-3">
                  {c.label}
                </th>
              ))}
              <th className="py-2">Allergies</th>
            </tr>
          </thead>
          <tbody>
            {[...sheet.rows, ...(showUnassigned ? [sheet.unassigned] : [])].map((r) => (
              <tr key={r.tableId || 'unassigned'} className="border-b border-slate-200 align-top">
                <td className="py-2 pr-3 font-semibold text-slate-900">{r.label}</td>
                <td className="py-2 pr-3">{r.pax || '—'}</td>
                {DIETARY_CATEGORIES.map((c) => (
                  <td key={c.key} className="py-2 pr-3">
                    {r.counts[c.key] || '—'}
                  </td>
                ))}
                <td className="py-2 text-xs text-slate-600">
                  {r.allergies.length === 0
                    ? '—'
                    : r.allergies.map((a, i) => (
                        <div key={i}>
                          <span className="font-medium">{a.guestName}:</span> {a.note}
                        </div>
                      ))}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <p className="mt-4 text-xs text-slate-400">
          Declined RSVPs excluded · counts are seats within each party · generated by SeatMap
        </p>
      </div>
    </div>
  )
}
